const SUPABASE_URL="https://toeamjaomjgamdmavdck.supabase.co";
const SUPABASE_ANON_KEY="sb_publishable_dVqF46Nccdn7i6pSBtahag_jCzxIYAR";
const LEVELS=["DPF10","DPF25","DPF35","DPF60","DPF100","DPF200","DPF500","DPF1000"];
const CATEGORIES=["Dame","Herre","Mix","Junior"];
const REGIONS=["Hovedstaden","Sjælland","Syddanmark","Midtjylland","Nordjylland"];
let tournaments=[],selectedLevels=[],selectedCategories=[],selectedRegions=[],visible=25;
const $=id=>document.getElementById(id);
const esc=v=>String(v??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[c]));
function chips(){$("levels").innerHTML=LEVELS.map(x=>`<button class="chip" data-l="${x}">${x}</button>`).join("");$("categories").innerHTML=CATEGORIES.map(x=>`<button class="chip" data-c="${x}">${x}</button>`).join("");$("regions").innerHTML=REGIONS.map(x=>`<button class="chip" data-r="${x}">${x}</button>`).join("");document.querySelectorAll("[data-l]").forEach(b=>b.onclick=()=>toggle(b.dataset.l,"l",b));document.querySelectorAll("[data-c]").forEach(b=>b.onclick=()=>toggle(b.dataset.c,"c",b));document.querySelectorAll("[data-r]").forEach(b=>b.onclick=()=>toggle(b.dataset.r,"r",b))}
function toggle(v,t,b){let a=t==="l"?selectedLevels:t==="c"?selectedCategories:selectedRegions;a=a.includes(v)?a.filter(x=>x!==v):[...a,v];if(t==="l")selectedLevels=a;else if(t==="c")selectedCategories=a;else selectedRegions=a;b.classList.toggle("active");visible=25;render()}
function classMatch(t){if(!selectedLevels.length&&!selectedCategories.length)return true;const cs=Array.isArray(t.classes)?t.classes:[];return cs.some(c=>{const ls=Array.isArray(c.level)?c.level:[],cats=Array.isArray(c.category)?c.category:[];return(!selectedLevels.length||selectedLevels.some(x=>ls.includes(x)))&&(!selectedCategories.length||selectedCategories.some(x=>cats.includes(x)))})}
function filtered(){const q=$("search").value.trim().toLowerCase(),f=$("dateFrom").value,to=$("dateTo").value;return tournaments.filter(t=>{const hay=[t.name,t.city,t.center,t.region].filter(Boolean).join(" ").toLowerCase();return(!q||hay.includes(q))&&classMatch(t)&&(!selectedRegions.length||selectedRegions.includes(t.region))&&(!f||t.tournament_date>=f)&&(!to||t.tournament_date<=to)})}
function fmtDate(v){if(!v)return"Ikke oplyst";const m=String(v).match(/^(\d{4})-(\d{2})-(\d{2})/);return m?`${m[3]}.${m[2]}.${m[1]}`:"Ikke oplyst"}
function fmtDeadline(v){if(!v)return"Ikke oplyst";const m=String(v).match(/^(\d{4})-(\d{2})-(\d{2})T(\d{2}):(\d{2})/);return m?`${m[3]}.${m[2]}.${m[1]} kl. ${m[4]}:${m[5]}`:"Ikke oplyst"}
function render(){const rows=filtered(),shown=rows.slice(0,visible);$("status").textContent=`${rows.length} turnering${rows.length===1?"":"er"} vises`;$("list").innerHTML=shown.length?shown.map(t=>`<article class="tournament-card"><div><h2 class="tournament-title">${esc(t.name)}</h2><div class="place-grid"><div class="place-pill city"><div><span class="place-label">By</span><span class="place-value">${esc(t.city||"Ikke oplyst")}</span></div></div><div class="place-pill"><div><span class="place-label">Center</span><span class="place-value">${esc(t.center||"Ikke oplyst")}</span></div></div></div></div><div class="info-grid"><div><span class="info-label">Turneringsdato</span><span class="info-value">${fmtDate(t.tournament_date)}</span></div><div><span class="info-label">Tilmeldingsfrist</span><span class="info-value">${fmtDeadline(t.deadline)}</span></div><div><span class="info-label">Region</span><span class="region-value">${esc(t.region||"Ikke oplyst")}</span></div></div>${t.rankedin_link?`<a class="card-action" href="${esc(t.rankedin_link)}" target="_blank">Se på Rankedin →</a>`:""}</article>`).join(""):`<div class="empty">Ingen turneringer matcher dine filtre.</div>`;$("more").hidden=rows.length<=visible}
async function load(){try{const today=new Date().toISOString().slice(0,10),u=new URL(`${SUPABASE_URL}/rest/v1/tournaments`);u.searchParams.set("select","*");u.searchParams.set("tournament_date",`gte.${today}`);u.searchParams.set("order","tournament_date.asc");const r=await fetch(u,{headers:{apikey:SUPABASE_ANON_KEY,Authorization:`Bearer ${SUPABASE_ANON_KEY}`,"Accept-Profile":"public"}});if(!r.ok)throw new Error(await r.text());tournaments=await r.json();render()}catch(e){$("status").textContent="Kunne ikke hente turneringer";$("list").innerHTML=`<div class="empty">${esc(e.message)}</div>`}}
$("search").oninput=()=>{visible=25;render()};$("dateFrom").onchange=render;$("dateTo").onchange=render;$("more").onclick=()=>{visible+=25;render()};$("reset").onclick=()=>{selectedLevels=[];selectedCategories=[];selectedRegions=[];$("search").value="";$("dateFrom").value="";$("dateTo").value="";document.querySelectorAll(".chip").forEach(x=>x.classList.remove("active"));render()};chips();load();
